name: Publish Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: elgohr/Publish-Docker-Github-Action@v5
        name: Build latest version and publish to GitHub Registry
        with:
          name: mileschou/hexo
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
